--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Muqsit/ChestShop
branches:
- master
projects:
  ChestShop:
    path: ""
    libs:
      - src: muqsit/InvMenu/InvMenu
        version: ^4.0.0
      - src: jojoe77777/FormAPI/libFormAPI
        version: 1.3.0
      - src: poggit/libasynql/libasynql
        version: ^3.3.1
...
