name: ChestShop
main: muqsit\chestshop\Loader
api: 5.3.0
version: 5.3.9
softdepend: [EconomyAPI, BedrockEconomy]
commands:
  chestshop:
    aliases: ["cs", "cshop"]
    permission: chestshop.command
permissions:
  chestshop.command:
    default: true
  chestshop.command.add:
    default: op
  chestshop.command.remove:
    default: op
  chestshop.command.help:
    default: op
