name: ChestShop
main: muqsit\chestshop\Loader
api: 4.0.0
version: 5.3.3
softdepend: [BedrockEconomy]
commands:
  chestshop:
    aliases: ["cs", "cshop"]
    permission: chestshop.command
permissions:
  chestshop.command:
    default: true
  chestshop.command.add:
    default: op
  chestshop.command.remove:
    default: op
  chestshop.command.help:
    default: op
